"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {Plus,Search,CookingPot,Clock,ArrowUpRight,Sun,Users,Leaf,BookOpen,Globe,Lock,ChevronRight,Utensils,RefreshCw,House} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {collection} from '@/lib/collection';
import {blankRecipe,matchesRecipe,mealAt,type Recipe,type Snapshot} from '@/lib/types';
import RecipeEditor from './recipe-editor';
import EmailSignIn from './email-signin';
import PasswordSettings from './password-settings';
import RecipeShare from './recipe-share';
import AccountMenu from './account-menu';
import {authClient,authFetch} from '@/lib/auth-client';
const empty:Snapshot={user:null,profile:null,kitchens:[],recipes:[]};
async function mutate(body:unknown){const res=await authFetch('/api/hub',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await res.json() as {error?:string;id:string;ok:boolean};if(!res.ok)throw Error(result.error||'Please try again.');return result;}
export default function Hub(){
 const [emailAuth,setEmailAuth]=useState(true);
 const refreshVersion=useRef(0);
 const [data,setData]=useState<Snapshot>(empty),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [tab,setTab]=useState('home'),[query,setQuery]=useState(''),[course,setCourse]=useState('All recipes'),[meal,setMeal]=useState('Dinner');
 const [headerScrolled,setHeaderScrolled]=useState(false);
 const [kitchenId,setKitchenId]=useState(''),[modal,setModal]=useState(''),[formError,setFormError]=useState(''),[busy,setBusy]=useState(false);
 const [selected,setSelected]=useState<Recipe|null>(null),[editing,setEditing]=useState<Recipe|null>(null),[checked,setChecked]=useState<number[]>([]);
 const [username,setUsername]=useState(''),[displayName,setDisplayName]=useState(''),[kitchenName,setKitchenName]=useState(''),[identifier,setIdentifier]=useState('');
 const refresh=useCallback(async()=>{const version=++refreshVersion.current;setError('');try{const res=await authFetch('/api/hub',{cache:'no-store'});const result=await res.json() as Snapshot & {error?:string};if(version!==refreshVersion.current)return null;if(!res.ok){if(res.status===401){setData(empty);setSelected(null);setEditing(null);}throw Error(result.error);}setData(result);setKitchenId(old=>result.kitchens.some((k:{id:string})=>k.id===old)?old:result.kitchens[0]?.id||'');return result as Snapshot;}catch(e){if(version===refreshVersion.current)setError(e instanceof Error?e.message:'Unable to load recipes.');return null;}finally{if(version===refreshVersion.current)setLoading(false);}},[]);
 useEffect(()=>{void refresh().then(d=>{if(d?.user&&!d.profile){setDisplayName(d.user.name);setModal('account');}});const params=new URLSearchParams(location.search);if(['home','kitchen','recipes'].includes(params.get('tab')||''))setTab(params.get('tab')!);const update=()=>setMeal(mealAt(new Date().getHours()));update();const timer=setInterval(update,60000);return()=>clearInterval(timer);},[refresh]);
 useEffect(()=>{let active=true;let unsubscribe=()=>{};void authClient().then(client=>{if(!active)return;setEmailAuth(!!client);if(!client)return;const {data:{subscription}}=client.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){++refreshVersion.current;setData(empty);setSelected(null);setEditing(null);setModal('');setTimeout(()=>{if(active)void refresh();},0);}});unsubscribe=()=>subscription.unsubscribe();}).catch(()=>{});return()=>{active=false;unsubscribe();};},[refresh]);
 useEffect(()=>{let frame=0;const update=()=>{frame=0;setHeaderScrolled(window.scrollY>20);};const queueUpdate=()=>{if(!frame)frame=window.requestAnimationFrame(update);};queueUpdate();window.addEventListener('scroll',queueUpdate,{passive:true});return()=>{window.removeEventListener('scroll',queueUpdate);if(frame)window.cancelAnimationFrame(frame);};},[]);
 const signedIn=async()=>{const result=await refresh();if(!result?.user)throw Error('Signed in, but your kitchen could not load. Please try again.');if(result.profile){setModal('');toast.success('Welcome back to Ajvar');}else{setUsername('');setDisplayName(result.user?.name||'');setModal('account');}};
 const signOut=async()=>{setBusy(true);try{const client=await authClient();if(client){const {error}=await client.auth.signOut({scope:'local'});if(error)throw error;setData(empty);setSelected(null);setEditing(null);setModal('');navigate('home');await refresh();toast.success('Signed out');}}catch{toast.error('Could not sign out. Please try again.');}finally{setBusy(false);}};
 const openModal=(name:string)=>{setFormError('');setModal(name);};
 const openAccount=()=>{setUsername(data.profile?.username||'');setDisplayName(data.profile?.name||data.user?.name||'');openModal('account');};
 const startRecipe=()=>{if(!data.profile){openAccount();return;}setEditing(blankRecipe());};
 const navigate=(next:string)=>{setTab(next);setQuery('');setCourse('All recipes');history.replaceState(null,'',next==='home'?'/':'/?tab='+next);if(window.matchMedia('(max-width:650px)').matches)window.scrollTo({top:0,behavior:'instant'});};
 useEffect(()=>{
  const ctx=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>Promise<void>}}).modelContext;
  if(!ctx?.registerTool)return;const life=new AbortController();
  const tools=[{name:'search_recipes',title:'Search recipes',description:'Search the public Discover view by recipe name, ingredients, description, cuisine or tags; changes the visible search.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:200}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const p=input as {query?:unknown};if(!p||typeof p.query!=='string'||p.query.length>200)throw Error('query must be text up to 200 characters.');setTab('home');setCourse('All recipes');setQuery(p.query);const result=[...data.recipes.filter(r=>r.visibility==='public'),...collection].filter(r=>matchesRecipe(r,p.query as string));return {query:p.query,count:result.length,recipes:result.map(r=>({id:r.id,title:r.title}))};}},{name:'start_recipe_creation',title:'Open recipe form',description:'Open the new recipe form. An account is required. This does not save a recipe.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Pass an empty object.');if(!data.profile)throw Error('Sign in and choose your Ajvar username first.');setEditing(blankRecipe());return {status:'recipe_form_open'};}}];
  for(const tool of tools){try{Promise.resolve(ctx.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}}
  return()=>life.abort();
 },[data.recipes,data.profile]);
 const kitchen=data.kitchens.find(k=>k.id===kitchenId);
 const source=tab==='home'?[...data.recipes.filter(r=>r.visibility==='public'),...collection]:tab==='recipes'?data.recipes.filter(r=>r.owner===data.user?.id):data.recipes.filter(r=>r.kitchenIds.includes(kitchenId));
 const found=source.filter(r=>(course==='All recipes'||r.course===course)&&matchesRecipe(r,query));
 if(tab==='home'&&course==='All recipes')found.sort((a,b)=>Number(b.course===meal)-Number(a.course===meal));
 const submitModal=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setFormError('');try{if(modal==='account')await mutate({action:'profile',username,name:displayName});if(modal==='kitchen'){const result=await mutate({action:'createKitchen',name:kitchenName});setKitchenId(result.id);setKitchenName('');navigate('kitchen');}if(modal==='member'){await mutate({action:'addMember',kitchenId,identifier});setIdentifier('');}await refresh();toast.success(modal==='member'?'Member added to your kitchen':modal==='kitchen'?'Your kitchen is ready':'Your Ajvar account is ready');setModal('');}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}};
 const saveRecipe=async(recipe:Recipe)=>{await mutate({action:'saveRecipe',recipe});await refresh();setEditing(null);setSelected(null);navigate('recipes');toast.success(recipe.id?'Recipe and sharing updated':'Recipe saved');};
 const openRecipe=(r:Recipe)=>{setChecked([]);setSelected(r);};
 return <div><Toaster position="bottom-right"/><header className={`topbar${headerScrolled?' is-scrolled':''}`}><a className="brand" href="/" aria-label="Ajvar home"><span className="brand-icon"><CookingPot/></span>ajvar<span className="brand-dot">.</span></a><Tabs className="main-navigation" value={tab} onValueChange={navigate}><TabsList aria-label="Main navigation" className="navtabs" variant="line"><TabsTrigger value="home"><House className="nav-icon" aria-hidden="true"/><span>Home</span></TabsTrigger><TabsTrigger value="kitchen"><CookingPot className="nav-icon" aria-hidden="true"/><span>My Kitchen</span></TabsTrigger><TabsTrigger value="recipes"><BookOpen className="nav-icon" aria-hidden="true"/><span>My recipes</span></TabsTrigger></TabsList></Tabs><div className="header-actions"><button className="button primary" onClick={startRecipe}><Plus size={18}/> Add a recipe</button>{data.profile?<AccountMenu profile={data.profile} emailAuth={emailAuth} busy={busy} onOpenAccount={openAccount} onOpenPassword={()=>openModal('password')} onSignOut={signOut}/>:<button className="account-link" onClick={openAccount} aria-label="Sign in or create account">Sign in</button>}</div></header>
 <main className="page"><div className="page-intro"><div><div className="eyebrow"><Sun size={15}/>{tab==='home'?'A LITTLE INSPIRATION FOR '+meal.toUpperCase():tab==='kitchen'?'YOUR PEOPLE. YOUR RECIPES.':'A RECIPE BOX OF YOUR OWN'}</div><h1>{tab==='home'?'What sounds good today?':tab==='kitchen'?'My Kitchen':'Made by you.'}</h1><p>{tab==='home'?'Old favourites. New discoveries. A place for every recipe.':tab==='kitchen'?'The recipes you share. The people you cook with.':'Your family favourites, exactly where you left them.'}</p></div><div className="handwritten">Good food,<br/>better together.</div></div>
 {error&&<div className="error-banner" role="alert">{error}<button onClick={()=>void refresh()}><RefreshCw size={15}/> Try again</button></div>}
 {tab==='kitchen'&&data.profile&&<><div className="kitchen-toolbar"><div className="kitchen-picker"><span className="note-icon"><CookingPot size={23}/></span>{data.kitchens.length>0?<Select value={kitchenId} onValueChange={setKitchenId}><SelectTrigger aria-label="Select kitchen"><SelectValue/></SelectTrigger><SelectContent>{data.kitchens.map(k=><SelectItem value={k.id} key={k.id}>{k.name}</SelectItem>)}</SelectContent></Select>:<strong>Your first kitchen is waiting</strong>}</div><button className="button outline" onClick={()=>openModal('kitchen')}><Plus size={16}/> New kitchen</button></div>{kitchen&&<div className="members-row"><div className="member-list">{kitchen.members.map(m=><span className="member-chip" key={m.id} title={'@'+m.username}><span className="mini-avatar">{m.name.charAt(0)}</span>{m.name}</span>)}</div><button className="text-button" onClick={()=>openModal('member')}><Users size={16}/> Add a member</button></div>}</>}
 {(tab==='home'||data.profile&&(tab==='recipes'||kitchen))&&<><div className="searchbox"><Search size={23}/><input aria-label="Search recipes" maxLength={200} placeholder="Search recipes, ingredients, or a little inspiration…" value={query} onChange={e=>setQuery(e.target.value)}/>{query?<button className="text-button" onClick={()=>setQuery('')}>Clear</button>:<span>Find your next favourite</span>}</div><div className="filterbar"><Tabs value={course} onValueChange={setCourse}><TabsList className="course-tabs">{['All recipes','Breakfast','Lunch','Dinner'].map(c=><TabsTrigger value={c} key={c}>{c}</TabsTrigger>)}</TabsList></Tabs><span className="small-note"><Leaf size={15}/>{tab==='home'?meal+' ideas first':'Something worth keeping'}</span></div><section><div className="section-heading"><h2>{query?'A little something for “'+query+'”':tab==='home'?'Fresh from the kitchen':tab==='recipes'?'Your recipe collection':kitchen?.name}</h2><span>{loading?'':found.length+' '+(found.length===1?'RECIPE':'RECIPES')}</span></div>{loading&&tab!=='home'?<div className="recipe-grid">{[0,1,2].map(i=><Skeleton key={i} className="h-72 w-full rounded-xl"/>)}</div>:found.length?<div className="recipe-grid">{found.map((r,i)=><article className={'recipe-card card-'+i%3} key={r.id}><button className="card-open" onClick={()=>openRecipe(r)} aria-label={'View '+r.title}><div className="recipe-art">{r.image?<img src={r.image} alt={r.title} loading={i>2?'lazy':'eager'} onError={e=>{e.currentTarget.style.display='none';}}/>:<div className="no-photo"><CookingPot size={44}/><span>From your recipe box</span></div>}<span className="recipe-course">{r.course}</span>{tab!=='home'&&<span className="visibility-icon" title={r.visibility} aria-label={r.visibility}>{r.visibility==='private'?<Lock size={14}/>:r.visibility==='kitchen'?<Users size={14}/>:<Globe size={14}/>}</span>}</div><div className="recipe-body"><div className="recipe-category">{[r.cuisine,r.tags.split(',')[0]].filter(Boolean).join(' · ')}</div><h3>{r.title}</h3><p>{r.description||'A recipe worth keeping and making again.'}</p><div className="card-bottom"><span><Clock size={15}/>{r.prep+r.cook} min</span><span>{r.author}<ArrowUpRight size={16}/></span></div></div></button></article>)}</div>:<Empty className="empty-state"><EmptyHeader><BookOpen size={32}/><EmptyTitle>{query||course!=='All recipes'?'Nothing in the recipe box just yet.':tab==='kitchen'?'Your shared table starts here.':'Let’s keep your first recipe.'}</EmptyTitle><EmptyDescription>{query||course!=='All recipes'?'Try another ingredient or view all recipes.':tab==='kitchen'?'Add a recipe and choose this kitchen in its sharing settings.':'That dish everyone asks for? Give it a home.'}</EmptyDescription></EmptyHeader><button className="button outline" onClick={()=>{if(query||course!=='All recipes'){setQuery('');setCourse('All recipes');}else startRecipe();}}>{query||course!=='All recipes'?'Clear filters':'Add a recipe'}</button></Empty>}</section></>}
 {tab!=='home'&&!data.profile&&!loading&&<Empty className="empty-state account-empty"><EmptyHeader><CookingPot size={42}/><EmptyTitle>Come on in. Make yourself at home.</EmptyTitle><EmptyDescription>Create your Ajvar account to keep recipes and cook together in a shared kitchen.</EmptyDescription></EmptyHeader><button className="button primary" onClick={openAccount}>Create your account <ChevronRight size={17}/></button></Empty>}
 {tab==='kitchen'&&data.profile&&!data.kitchens.length&&<Empty className="empty-state"><EmptyHeader><Users size={38}/><EmptyTitle>Who’s in your kitchen?</EmptyTitle><EmptyDescription>Give your kitchen a name, add your people, and start sharing recipes.</EmptyDescription></EmptyHeader><button className="button primary" onClick={()=>openModal('kitchen')}>Create a kitchen</button></Empty>}
 {tab==='home'&&<section className="kitchen-note"><span className="note-icon"><Users size={30}/></span><div><h2>A kitchen is better with company.</h2><p>Keep your family favourites together in your own shared kitchen.</p></div><button className="button outline" onClick={()=>navigate('kitchen')}>Make yourself at home <ArrowUpRight size={17}/></button></section>}
 <footer><a className="footer-brand" href="/">ajvar.</a><span>A little love in every recipe.</span><span>Your family’s kitchen hub</span></footer></main>
 <Dialog open={!!modal} onOpenChange={open=>{if(!open&&!busy)setModal('');}}><DialogContent className="ajvar-dialog"><DialogHeader><DialogTitle>{modal==='password'?'Set or change password':modal==='account'?(data.profile?'Account settings':'Welcome to Ajvar'):modal==='kitchen'?'A kitchen of your own':'Room for one more'}</DialogTitle><DialogDescription>{modal==='password'?'Keep your account and recipes, and choose how you sign in.':modal==='account'?(data.profile?'Update the details your family and kitchen members see.':data.user?'Your username makes it easy for family to find you.':emailAuth?'Log in with a password or email code, or create an account.':'Sign in with ChatGPT, then choose your Ajvar username.'):modal==='kitchen'?'A home for the recipes you cook together.':'Add someone with an existing Ajvar account.'}</DialogDescription></DialogHeader>
 {modal==='password'&&data.user&&emailAuth?<PasswordSettings key={data.user.id} email={data.user.email} onBusy={setBusy} onBack={()=>openModal('account')}/>:modal==='account'&&!data.user?(emailAuth?<EmailSignIn onSignedIn={signedIn} onBusy={setBusy}/>:<div className="signin-content"><div className="signin-mark"><CookingPot size={36}/></div><p>Keep recipes private, share with your people, or put a favourite on the public table.</p><a className="button primary" target="_top" href={'/signin-with-chatgpt?return_to='+encodeURIComponent('/?tab='+tab)}>Continue with ChatGPT <ArrowUpRight size={17}/></a><p className="form-help">New here? Your Ajvar account is created after you choose a username.</p></div>):<form onSubmit={submitModal} className="simple-form"><fieldset disabled={busy}>{modal==='account'?<><label>Your name<input value={displayName} onChange={e=>setDisplayName(e.target.value)} required maxLength={80} autoComplete="name"/></label><label>Username<div className="username-field"><span>@</span><input aria-label="Username" value={username} onChange={e=>setUsername(e.target.value.toLowerCase())} required pattern="[a-z0-9_]{3,24}" minLength={3} maxLength={24} autoComplete="username" placeholder="e.g. anna_cooks"/></div></label><p className="form-help">3–24 lowercase letters, numbers or underscores.</p><label>Account email<input readOnly value={data.user?.email||''}/></label></>:modal==='kitchen'?<label>Kitchen name<input value={kitchenName} onChange={e=>setKitchenName(e.target.value)} placeholder="e.g. The Andersen kitchen" required minLength={2} maxLength={80} autoFocus/></label>:<><label>Username or account email<input value={identifier} onChange={e=>setIdentifier(e.target.value)} required minLength={3} maxLength={254} placeholder="@anna_cooks or anna@example.com" autoFocus/></label><p className="form-help">They’ll have access to every recipe shared with {kitchen?.name}. No email is sent.</p></>}{formError&&<p className="form-error" role="alert">{formError}</p>}<button className="button primary" type="submit">{busy?'Saving…':modal==='account'?(data.profile?'Save changes':'Create account'):modal==='kitchen'?'Create kitchen':'Add to kitchen'}</button></fieldset></form>}</DialogContent></Dialog>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="ajvar-dialog recipe-detail">{selected&&<><DialogHeader><div className="recipe-category">{selected.course} · {selected.cuisine}</div><DialogTitle>{selected.title}</DialogTitle><DialogDescription>{selected.description||'From '+selected.author+'’s recipe box.'}</DialogDescription></DialogHeader>{selected.image&&<img className="detail-photo" src={selected.image} alt={selected.title}/>}<div className="detail-meta"><span><Clock size={17}/>Prep {selected.prep} min · Cook {selected.cook} min</span><span><Utensils size={17}/>{selected.servings} servings</span></div><div className="byline">By {selected.author} <span>{selected.visibility==='private'?'Private recipe':selected.visibility==='kitchen'?'Shared with a kitchen':'Public recipe'}</span></div>{selected.owner===data.user?.id&&<button className="button outline" onClick={()=>{setEditing(selected);setSelected(null);}}>Edit recipe & sharing <ArrowUpRight size={16}/></button>}<RecipeShare key={selected.id+":"+String(selected.owner===data.user?.id)} recipe={selected} isOwner={selected.owner===data.user?.id}/><div className="recipe-instructions"><section><h2>Ingredients</h2><p className="form-help">Tick off as you cook.</p><div className="ingredient-checks">{selected.ingredients.map((ing,i)=><label key={i} className={checked.includes(i)?'is-checked':''}><Checkbox checked={checked.includes(i)} onCheckedChange={v=>setChecked(old=>v?[...old,i]:old.filter(n=>n!==i))}/><span><strong>{ing.amount} {ing.unit}</strong> {ing.name}</span></label>)}</div></section><section><h2>Let’s make it</h2><ol className="method">{selected.steps.map((step,i)=><li key={i}><span>{i+1}</span><p>{step}</p></li>)}</ol></section></div>{selected.credit&&<p className="photo-credit">Photo: <a target="_blank" rel="noreferrer" href={selected.credit.url}>{selected.credit.label}</a>. Serving inspiration.</p>}</>}</DialogContent></Dialog>
 {editing&&<RecipeEditor initial={editing} kitchens={data.kitchens} onClose={()=>setEditing(null)} onSave={saveRecipe}/>}
 </div>;
}
