"use client";
import {useState} from 'react';
import {Plus,Trash2,ArrowUp,ArrowDown,Lock,Users,Globe,Check} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import type {Recipe,Kitchen} from '@/lib/types';
function Choice({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <label>{label}<Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem value={v} key={v}>{v.charAt(0).toUpperCase()+v.slice(1)}</SelectItem>)}</SelectContent></Select></label>}
export default function RecipeEditor({initial,kitchens,onClose,onSave}:{initial:Recipe;kitchens:Kitchen[];onClose:()=>void;onSave:(r:Recipe)=>Promise<void>}){
 const [r,setR]=useState<Recipe>(structuredClone(initial)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[discard,setDiscard]=useState(false);
 const update=<K extends keyof Recipe>(key:K,value:Recipe[K])=>setR(old=>({...old,[key]:value}));
 const requestClose=()=>{if(busy)return;if(JSON.stringify(r)!==JSON.stringify(initial))setDiscard(true);else onClose();};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(r.visibility==='kitchen'&&!r.kitchenIds.length){setError('Choose at least one kitchen, or save privately for now.');return;}setBusy(true);try{await onSave({...r,kitchenIds:r.visibility==='private'?[]:r.kitchenIds});}catch(e){setError((e as Error).message);setBusy(false);}};
 const move=(i:number,d:number)=>{const steps=[...r.steps];[steps[i],steps[i+d]]=[steps[i+d],steps[i]];update('steps',steps);};
 return <><Dialog open onOpenChange={open=>{if(!open)requestClose();}}><DialogContent className="ajvar-dialog recipe-editor" onInteractOutside={e=>e.preventDefault()}><DialogHeader><div className="eyebrow">FROM YOUR KITCHEN, WITH LOVE</div><DialogTitle>{initial.id?'A little fine-tuning.':'Something worth keeping.'}</DialogTitle><DialogDescription>{initial.id?'Update the recipe or change who gets a place at the table.':'Write it down once. Make it again and again.'}</DialogDescription></DialogHeader><form onSubmit={submit}><fieldset disabled={busy}><section className="form-section"><div className="form-section-title"><span>01</span><h2>The essentials</h2></div><label>Recipe name<input value={r.title} onChange={e=>update('title',e.target.value)} placeholder="e.g. Mum’s roasted pepper ajvar" required minLength={2} maxLength={140}/></label><label>A little about this recipe<textarea rows={2} value={r.description} onChange={e=>update('description',e.target.value)} placeholder="What makes it special? Add a description to help people find it." maxLength={2000}/></label><div className="form-grid"><Choice label="Meal course" value={r.course} options={['Breakfast','Lunch','Dinner','Snack','Dessert','Side']} onChange={v=>update('course',v)}/><label>Cuisine <span className="optional">optional</span><input value={r.cuisine} onChange={e=>update('cuisine',e.target.value)} placeholder="e.g. Italian, Balkan" maxLength={80}/></label></div><div className="form-grid three">{[['prep','Prep time (min)'],['cook','Cook time (min)'],['servings','Servings']].map(([key,label])=><label key={key}>{label}<input type="number" required min={key==='servings'?1:0} max={key==='servings'?1000:key==='prep'?1440:2880} value={Number.isNaN(r[key as 'prep'|'cook'|'servings'])?'':r[key as 'prep'|'cook'|'servings']} onChange={e=>update(key as 'prep'|'cook'|'servings',e.target.value===''?NaN:Number(e.target.value))}/></label>)}</div><label>Tags <span className="optional">optional</span><input value={r.tags} onChange={e=>update('tags',e.target.value)} placeholder="e.g. Vegetarian, gluten-free, family favourite" maxLength={250}/></label><p className="form-help">Tags, cuisine and ingredients are all searchable.</p><label>Photo URL <span className="optional">optional</span><input type="url" value={r.image} onChange={e=>update('image',e.target.value)} placeholder="https://…" maxLength={2000}/></label></section>
 <section className="form-section"><div className="form-section-title"><span>02</span><h2>What goes in</h2></div><div className="ingredient-head"><span>Amount</span><span>Unit</span><span>Ingredient</span></div>{r.ingredients.map((ing,i)=><div className="ingredient-row" key={i}>{(['amount','unit','name'] as const).map(key=><input key={key} aria-label={'Ingredient '+(i+1)+' '+key} value={ing[key]} placeholder={key==='amount'?'2':key==='unit'?'tbsp':'e.g. olive oil'} required={key==='name'} maxLength={key==='name'?250:30} onChange={e=>update('ingredients',r.ingredients.map((a,j)=>j===i?{...a,[key]:e.target.value}:a))}/>)}<button className="icon-button" type="button" aria-label={'Remove ingredient '+(i+1)} disabled={r.ingredients.length===1} onClick={()=>update('ingredients',r.ingredients.filter((_,j)=>i!==j))}><Trash2 size={16}/></button></div>)}<button className="text-button add-row" type="button" disabled={r.ingredients.length>=100} onClick={()=>update('ingredients',[...r.ingredients,{amount:'',unit:'',name:''}])}><Plus size={16}/> Add an ingredient</button></section>
 <section className="form-section"><div className="form-section-title"><span>03</span><h2>How it comes together</h2></div>{r.steps.map((step,i)=><div className="step-row" key={i}><span className="step-number">{i+1}</span><textarea aria-label={'Step '+(i+1)} rows={3} required maxLength={3000} value={step} placeholder={i===0?'Start with the first step…':'What happens next?'} onChange={e=>update('steps',r.steps.map((s,j)=>i===j?e.target.value:s))}/><div className="step-controls"><button className="icon-button" aria-label={'Move step '+(i+1)+' up'} type="button" disabled={i===0} onClick={()=>move(i,-1)}><ArrowUp size={15}/></button><button className="icon-button" aria-label={'Move step '+(i+1)+' down'} type="button" disabled={i===r.steps.length-1} onClick={()=>move(i,1)}><ArrowDown size={15}/></button><button className="icon-button" aria-label={'Remove step '+(i+1)} type="button" disabled={r.steps.length===1} onClick={()=>update('steps',r.steps.filter((_,j)=>i!==j))}><Trash2 size={15}/></button></div></div>)}<button className="text-button add-row" type="button" disabled={r.steps.length>=60} onClick={()=>update('steps',[...r.steps,''])}><Plus size={16}/> Add a step</button></section>
 <section className="form-section sharing-section"><div className="form-section-title"><span>04</span><h2>Who’s at the table?</h2></div><Choice label="Recipe visibility" value={r.visibility} options={['private','kitchen','public']} onChange={v=>update('visibility',v as Recipe['visibility'])}/><p className="sharing-help">{r.visibility==='private'?<Lock size={17}/>:r.visibility==='kitchen'?<Users size={17}/>:<Globe size={17}/>}<span>{r.visibility==='private'?'Only you can see this recipe. Saving as private removes its kitchen shares.':r.visibility==='kitchen'?'Only you and members of the selected kitchens can see this recipe.':'Anyone who can visit Ajvar can find and read this recipe on Home.'}</span></p>{r.visibility!=='private'&&<><h3 className="sharing-label">{r.visibility==='public'?'Also share with your kitchens':'Share with these kitchens'}</h3>{kitchens.length?kitchens.map(k=><label className="kitchen-check" key={k.id}><Checkbox checked={r.kitchenIds.includes(k.id)} onCheckedChange={v=>update('kitchenIds',v?[...r.kitchenIds,k.id]:r.kitchenIds.filter(id=>id!==k.id))}/><span>{k.name}</span><span>{k.members.length} members</span></label>):<p className="form-help">Create a kitchen from My Kitchen first, or save this recipe privately for now.</p>}<p className="form-help">Sharing stays in place until you edit these settings.</p></>}</section>
 {error&&<div className="form-error" role="alert">{error}</div>}<div className="editor-footer"><span>{r.visibility==='private'?<Lock size={15}/>:r.visibility==='kitchen'?<Users size={15}/>:<Globe size={15}/>} {r.visibility==='private'?'Just for you':r.visibility==='kitchen'?'For your kitchen':'For the public table'}</span><button type="button" className="button outline" onClick={requestClose}>Cancel</button><button type="submit" className="button primary"><Check size={17}/>{busy?'Saving…':'Save recipe'}</button></div></fieldset></form></DialogContent></Dialog><AlertDialog open={discard} onOpenChange={setDiscard}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Leave your changes behind?</AlertDialogTitle><AlertDialogDescription>Your changes have not been saved. Keep editing to finish your recipe.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep editing</AlertDialogCancel><AlertDialogAction onClick={onClose}>Discard changes</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
